name: PHP CS Fixer

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Check commit message for skip
        id: check_skip
        run: echo "SKIP-PHP-CS-FIXER=$(git log -1 --pretty=%B | grep -c '[SKIP-PHPCS]')" >> $GITHUB_ENV

      - name: Run PHP-CS-Fixer
        if: env.SKIP-PHP-CS-FIXER != '1'
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php

      - name: Auto commit changes
        if: env.SKIP-PHP-CS-FIXER != '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autocommit PHP CS Fixer
